#!url=https://vantuan2703 x/module/b612.module
#!name=B612.mudule
#!desc= By: ѵăռŧυấռ 💤
#!homepage=https://vantuan2703 x
#!author=ddgksf2013
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/b612.png
[Script]
B612咔叽=type=http-response,pattern=https://user-kaji-api.b612kaji.com/v1/purchase/subscription/subscriber/status,requires-body=1,script-path=https://github.com/deezertidal/private/raw/master/js-backup/Crack/612.js
[MITM]
hostname = %APPEND% user-kaji-api.b612kaji.com