#!url=https://vantuan2703 x/module/photoroom.module
#!name=PhotoRoom.mudule
#!desc= By: ѵăռŧυấռ 💤
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/Plugallery.png
#!homepage=https://vantuan2703 x
#!author=89996462
[Script]
PhotoRoom=type=http-response,pattern=^https?:\/\/api\.revenuecat\.com\/v1\/(subscribers\/[^\/]+$|receipts$),requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/PhotoRoom.js



[MITM]
hostname = %APPEND% api.revenuecat.com
