#!url=https://vantuan2703 x/module/picsart.module
#!name=Picsart 💤.mudule
#!desc= By: ѵăռŧυấռ 💤
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/picsart.png
#!homepage=https://vantuan2703 x
#!author=NobyDa
[Script]
Picsart=type=http-response,pattern=https:\/\/api\.(picsart|meiease)\.c(n|om)\/users\/show\/me\.json,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/Surge/JS/PicsArt.js

[MITM]
hostname = %APPEND% api.picsart.c*, api.meiease.c*
